### ISSUE TITLE
USER STORY: Hide the poll

### ISSUE THREAD

**Issue by Brindusa22** [Brindusa22/My-First-Agile-Project#7]
As an **administrator** I can **pick the expiry date while publishing the poll** so that **the poll can hide automatically**

## Acceptance Criteria:

* The poll should disappear at 11:59 PM on the target date
* The real estate of the "Poll" should be reserved on the home page; a message saying: "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active
*  The administrator expiry date should be at least 3 days after the current date

## Tasks:

- [x] Update the admin module view: the poll design(HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay Tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days
- [ ] Create a job to check expired Polls everyday at 11:59 PM and hide them
- [ ] Update the controller function
- [ ] Update unit test scripts 
- [ ] Test the functionality
